### ISSUE TITLE
ModuleNotFoundError: No module named 'sqflint'

### ISSUE THREAD

**Issue by Sparker95** [LordGolias/SublimeLinter-contrib-sqflint#5]
Hi!
I was following the instructions and installed the module for Sublime 3, however it was not working.
I'm new to sublime and its modules.  I tried to debug it by enabling the debug mode in SublimeLint and that's what it gives to me when I try to open the SQF file:
```D:\temp\tasks  (working dir)
  > type Tasks\fn_taskAlwaysVisible.sqf | C:\Python\Python36-32\Scripts\sqflint.exe

SublimeLinter: #1 linter.py:500: WARNING: sqflint output:
Traceback (most recent call last):
  File "c:\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python36-32\Scripts\sqflint.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'sqflint'

SublimeLinter: #1 linter.py:502: Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: sublime_linter.py:288: Linting buffer 25 took 0.14s
Package Control: Skipping automatic upgrade, last run at 2018-05-18 01:50:08, next run at 2018-05-18 02:50:08 or after```

It seems that my setup is correct and the SublimeLint and sqflint have found each other, but there's an error in the python code.

**Comment by Sparker95** [comment]
sqflint.py works fine on its own. I've re-made an .exe from it with PyInstaller and it seems to be working with Sublime now.

**Comment by jonpas** [comment]
Related: https://github.com/SublimeLinter/SublimeLinter/issues/1462#issuecomment-407111901

**Comment by jonpas** [comment]
Solved with adding the following to SublimeLinter settings:
```json
"linters": {
  "sqflint": {
      "executable": ["sqflint"]
  }
}
```

And in addition you have to fix `sqflint` installation itself (basically what you did with your own `.exe` but through `pip`):
`pip install git+https://github.com/LordGolias/sqf.git --upgrade`
(ref. https://github.com/LordGolias/sqf/issues/22#issuecomment-524392478)

**Comment by TheRealSpaceHippo** [comment]
Just thought I'd add my experience with the same issue:

- I tried to do the `pip install git+https://github.com/LordGolias/sqf.git --upgrade` however I then got an error similar to "No command named git" (sorry can't remember exactly what it said).
- I installed [git](https://gitforwindows.org/) after realizing that was the problem
- Closed and reopened the command prompt and attempted to do `pip install git+https://github.com/LordGolias/sqf.git --upgrade` again
- It worked! 😄
